<?php
defined('InShopNC') or exit('Access Invalid!');
$style_data = array(
	'default' => array('truename'=>'我的默认小店'), 
	'style1' => array('truename'=>'AppleStore'),
	'style2' => array('truename'=>'中式水墨典雅'),
	'style3' => array('truename'=>'蓝粉卡通玩具'),
	'style4' => array('truename'=>'木纹爱心宠物'),
	'style5' => array('truename'=>'纯色简约线条'),
	'style6' => array('truename'=>'AppleStore'),
	'style7' => array('truename'=>'中式水墨典雅'),
	'style8' => array('truename'=>'蓝粉卡通玩具'),
	'style9' => array('truename'=>'木纹爱心宠物'),
	'style10' => array('truename'=>'纯色简约线条'),
	'style11' => array('truename'=>'AppleStore'),
	'style12' => array('truename'=>'中式水墨典雅'),
	'style13' => array('truename'=>'蓝粉卡通玩具'),
	'style14' => array('truename'=>'木纹爱心宠物'),
	'style15' => array('truename'=>'纯色简约线条'),
	'style16' => array('truename'=>'AppleStore'),
	'style17' => array('truename'=>'中式水墨典雅'),
	'style18' => array('truename'=>'蓝粉卡通玩具'),
	'style19' => array('truename'=>'木纹爱心宠物'),
	'style20' => array('truename'=>'纯色简约线条'),
	'style21' => array('truename'=>'AppleStore'),
	'style22' => array('truename'=>'中式水墨典雅'),
	'style23' => array('truename'=>'蓝粉卡通玩具'),
	'style24' => array('truename'=>'木纹爱心宠物'),
	'style25' => array('truename'=>'纯色简约线条'),
	'style26' => array('truename'=>'AppleStore'),
	'style27' => array('truename'=>'中式水墨典雅'),
	'style28' => array('truename'=>'蓝粉卡通玩具'),
	'style29' => array('truename'=>'木纹爱心宠物'),
	'style30' => array('truename'=>'纯色简约线条'),
	'style31' => array('truename'=>'AppleStore'),
	'style32' => array('truename'=>'中式水墨典雅'),
	'style33' => array('truename'=>'蓝粉卡通玩具'),
	'style34' => array('truename'=>'木纹爱心宠物'),
	'style35' => array('truename'=>'纯色简约线条'),
	'style36' => array('truename'=>'AppleStore'),
	'style37' => array('truename'=>'中式水墨典雅'),
	'style38' => array('truename'=>'蓝粉卡通玩具'),
	'style39' => array('truename'=>'木纹爱心宠物')
);
?>